src/Entity/Carburant/Plein.php
<?php

namespace App\Entity\Carburant;

use App\Repository\Carburant\PleinRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PleinRepository::class)]
class Plein
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private $date;

    #[ORM\Column(type: 'integer')]
    private $quantite;

    #[ORM\Column(type: 'integer')]
    private $prix;

    #[ORM\Column(type: 'integer')]
    private $kilometrage;

    #[ORM\ManyToOne(targetEntity: Voiture::class, inversedBy: 'pleins')]
    #[ORM\JoinColumn(nullable: false)]
    private $voiture;

    #[ORM\ManyToOne(targetEntity: Station::class, inversedBy: 'pleins')]
    private $station;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getKilometrage(): ?int
    {
        return $this->kilometrage;
    }

    public function setKilometrage(int $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): self
    {
        $this->voiture = $voiture;

        return $this;
    }

    public function getPrixAuLitre()
    {
        return $this->getPrix() / $this->getQuantite();
    }

    public function getStation(): ?Station
    {
        return $this->station;
    }

    public function setStation(?Station $station): self
    {
        $this->station = $station;

        return $this;
    }
}

src/Entity/Carburant/Station.php
<?php

namespace App\Entity\Carburant;

use App\Repository\Carburant\StationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StationRepository::class)]
class Station
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 30)]
    private $nom;

    #[ORM\Column(type: 'string', length: 30)]
    private $ville;

    #[ORM\OneToMany(mappedBy: 'station', targetEntity: Plein::class)]
    private $pleins;

    public function __construct()
    {
        $this->pleins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection<int, Plein>
     */
    public function getPleins(): Collection
    {
        return $this->pleins;
    }

    public function addPlein(Plein $plein): self
    {
        if (!$this->pleins->contains($plein)) {
            $this->pleins[] = $plein;
            $plein->setStation($this);
        }

        return $this;
    }

    public function setPleins(?Collection $pleins): self
    {
        $this->pleins = $pleins;

        return $this;
    }
    
    public function removePlein(Plein $plein): self
    {
        if ($this->pleins->removeElement($plein)) {
            // set the owning side to null (unless already changed)
            if ($plein->getStation() === $this) {
                $plein->setStation(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom . ' ' . $this->ville;
    }

    public function sortPleins(string $sort, string $order): self
    {
        $pleins = $this->getPleins()->getValues();
        $s = $this;
        usort($pleins, function ($a, $b) use ($s, $sort, $order) {
            $return = 0;
            if ($sort == 'date') {
                $return = $b->getDate() <=> $a->getDate();
            } elseif ($sort == 'prix') {
                $return = $b->getPrix() <=> $a->getPrix();
            } elseif ($sort == 'quantite') {
                $return = $b->getQuantite() <=> $a->getQuantite();
            } elseif ($sort == 'kilometrage') {
                $return = $b->getKilometrage() <=> $a->getKilometrage();
            } elseif ($sort == 'prix_au_litre') {
                $return = $b->getPrixAuLitre() <=> $a->getPrixAuLitre();
            }
            if ($order == 'asc' || $order == 'ASC') {
                $return *= -1;
            }
            return $return;
        });
        $this->setPleins(new ArrayCollection($pleins));
        return $this;
    }
}

src/Entity/Carburant/Voiture.php
<?php

namespace App\Entity\Carburant;

use App\Repository\Carburant\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;


    #[ORM\OneToMany(mappedBy: 'voiture', targetEntity: Plein::class)]
    #[ORM\OrderBy(['date' => 'DESC'])]
    private $pleins;

    #[ORM\Column(type: 'string', length: 30)]
    private $marque;

    #[ORM\Column(type: 'string', length: 30)]
    private $modele;

    #[ORM\Column(type: 'string', length: 10)]
    private $immatriculation;

    public function __construct()
    {
        $this->pleins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Plein>
     */
    public function getPleins(): Collection
    {
        return $this->pleins;
    }

    public function addPlein(Plein $plein): self
    {
        if (!$this->pleins->contains($plein)) {
            $this->pleins[] = $plein;
            $plein->setVoiture($this);
        }

        return $this;
    }

    public function removePlein(Plein $plein): self
    {
        if ($this->pleins->removeElement($plein)) {
            // set the owning side to null (unless already changed)
            if ($plein->getVoiture() === $this) {
                $plein->setVoiture(null);
            }
        }

        return $this;
    }

    public function setPleins(?Collection $pleins): self
    {
        $this->pleins = $pleins;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getImmatriculation(): ?string
    {
        return $this->immatriculation;
    }

    public function setImmatriculation(string $immatriculation): self
    {
        $this->immatriculation = $immatriculation;

        return $this;
    }

    public function __toString()
    {
        return $this->marque . ' ' . $this->modele;
    }

    public function getMontantTotal(): ?int
    {
        $total = 0;
        foreach ($this->pleins as $plein) {
            $total += $plein->getPrix();
        }
        return $total;
    }

    public function getKilometresParcourus(Plein $plein): ?int
    {

        $pleins = $this->getPleins()->getValues();
        if(count($pleins) == 0) return 0;
        
        usort($pleins, function ($a, $b) {
            return $b->getDate() <=> $a->getDate();
        });
        foreach ($pleins as $key => $p) {
            if ($p->getId() == $plein->getId()) {
                if ($key == 0) {
                    return 0;
                } else {
                    return $pleins[$key - 1]->getKilometrage() - $p->getKilometrage();
                }
            }
        }

    }

    public function getKilometresTotal(): ?int
    {
        $pleins = $this->getPleins()->getValues();
        if(count($pleins) == 0){
            return 0;
        }

        usort($pleins, function ($a, $b) {
            return $b->getDate() <=> $a->getDate();
        });
        return $pleins[0]->getKilometrage() - $pleins[count($pleins) - 1]->getKilometrage();
    }

    public function getPrixMoyenPlein(): ?int
    {
        $pleins = $this->getPleins();
        $total = 0;
        foreach ($pleins as $plein) {
            $total += $plein->getPrix();
        }
        return $total / $pleins->count();
    }

    public function getPrixMoyenLitre(): ?int
    {
        $pleins = $this->getPleins();
        $prixTotal = 0;
        $quantiteTotal = 0;
        foreach ($pleins as $plein) {
            $prixTotal += $plein->getPrix();
            $quantiteTotal += $plein->getQuantite();
        }
        return $prixTotal / $quantiteTotal * 100;
    }

    public function sortPleins(string $sort, string $order): self
    {
        $pleins = $this->getPleins()->getValues();
        $v = $this;
        usort($pleins, function ($a, $b) use ($v, $sort, $order) {
            $return = 0;
            if ($sort == 'date') {
                $return = $b->getDate() <=> $a->getDate();
            } elseif ($sort == 'prix') {
                $return = $b->getPrix() <=> $a->getPrix();
            } elseif ($sort == 'quantite') {
                $return = $b->getQuantite() <=> $a->getQuantite();
            } elseif ($sort == 'kilometrage') {
                $return = $b->getKilometrage() <=> $a->getKilometrage();
            } elseif ($sort == 'station') {
                $return = $b->getStation()?->getNom() <=> $a->getStation()?->getNom();
            } elseif ($sort == 'prix_au_litre') {
                $return = $b->getPrixAuLitre() <=> $a->getPrixAuLitre();
            } elseif ($sort == 'kilometre_parcourus') {
                $return = $v->getKilometresParcourus($b) <=> $v->getKilometresParcourus($a);
            }
            if ($order == 'asc' || $order == 'ASC') {
                $return *= -1;
            }
            return $return;
        });
        $this->setPleins(new ArrayCollection($pleins));
        return $this;
    }


}

src/Form/Carburant/PleinType.php
<?php

namespace App\Form\Carburant;

use App\Entity\Carburant\Plein;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PleinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('quantite')
            ->add('prix')
            ->add('kilometrage')
            ->add('voiture')
            ->add('station')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Plein::class,
        ]);
    }
}

src/Form/Carburant/StationType.php
<?php

namespace App\Form\Carburant;

use App\Entity\Carburant\Station;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('ville')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Station::class,
        ]);
    }
}

src/Form/Carburant/VoitureType.php
<?php

namespace App\Form\Carburant;

use App\Entity\Carburant\Voiture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoitureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('marque')
            ->add('modele')
            ->add('immatriculation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Voiture::class,
        ]);
    }
}

src/Controller/Carburant/VoitureController.php
<?php

namespace App\Controller\Carburant;

use App\Entity\Carburant\Voiture;
use App\Form\Carburant\VoitureType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\Carburant\VoitureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/voiture')]
class VoitureController extends AbstractController
{
    #[Route('/', name: 'app_voiture_index', methods: ['GET'])]
    public function index(VoitureRepository $voitureRepository): Response
    {
        return $this->render('carburant/voiture/index.html.twig', [
            'voitures' => $voitureRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_voiture_new', methods: ['GET', 'POST'])]
    public function new(Request $request, VoitureRepository $voitureRepository): Response
    {
        $voiture = new Voiture();
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $voitureRepository->add($voiture, true);

            return $this->redirectToRoute('app_voiture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('carburant/voiture/new.html.twig', [
            'voiture' => $voiture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_voiture_show', methods: ['GET'])]
    public function show(Request $request, Voiture $voiture): Response
    {
        $sort = $request->query->get('sort', 'date');
        $order = $request->query->get('order', 'desc');
        $voiture->sortPleins($sort, $order);
        return $this->render('carburant/voiture/show.html.twig', [
            'voiture' => $voiture,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_voiture_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Voiture $voiture, VoitureRepository $voitureRepository): Response
    {
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $voitureRepository->add($voiture, true);

            return $this->redirectToRoute('app_voiture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('carburant/voiture/edit.html.twig', [
            'voiture' => $voiture,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_voiture_delete', methods: ['POST'])]
    public function delete(Request $request, Voiture $voiture, VoitureRepository $voitureRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voiture->getId(), $request->request->get('_token'))) {
            $voitureRepository->remove($voiture, true);
        }

        return $this->redirectToRoute('app_voiture_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/carburant/voiture/_delete_form.html.twig
<form method="post" action="{{ path('app_voiture_delete', {'id': voiture.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cette voiture?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voiture.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/carburant/voiture/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/carburant/voiture/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la voiture{% endblock %}

{% block body %}
    <h1>Modifier la voiture</h1>

    {{ include('voiture/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-default btn-sm" role="buttun" href="{{ path('app_voiture_index') }}">Retour à la liste</a>

    {% if is_granted('ROLE_ADMIN') %}{{ include('voiture/_delete_form.html.twig') }}{% endif %}
{% endblock %}

templates/carburant/voiture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voitures{% endblock %}

{% block body %}
    <h1 class="mt-5">Voitures</h1>

    <table class="table table-sm table-hover mt-3">
        <thead>
            <tr>
                <th>#</th>
                <th></th>
                <th>Kilomètres parcourus</th>
                <th>Prix total</th>
            </tr>
        </thead>
        <tbody>
        {% for voiture in voitures %}
            <tr onclick="window.location='{{ path('app_voiture_show', {'id': voiture.id}) }}';" style="cursor:pointer;">
                <th>{{ loop.index }}</th>
                <th>{{ voiture.marque }} {{ voiture.modele }}</th>
                <td>{{ (voiture.kilometresTotal) | number_format(0, '.', ' ')}}km</td>
                <td>{{ (voiture.montantTotal / 100) | number_format(2, '.', ' ')}}€</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/carburant/voiture/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Voiture{% endblock %}

{% block body %}
    <h1>Create new Voiture</h1>

    {{ include('voiture/_form.html.twig') }}

    <a href="{{ path('app_voiture_index') }}">back to list</a>
{% endblock %}

templates/carburant/voiture/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voiture{% endblock %}

{% block body %}
    <h1 class="mt-5">
        {{ voiture.marque }} {{ voiture.modele }}
    </h1>
    <table class="table table-sm table-striped">
        <thead>
            <tr>
                <th>Montant total</th>
                <th>Kilomètres total</th>
                <th>Prix moyen d'un plein</th>
                <th>Prix moyen du litre</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ (voiture.montantTotal / 100) | number_format(2, '.', ' ')}}€</td>
                <td>{{ (voiture.kilometresTotal) | number_format(0, '.', ' ')}}km</td>
                <td>{{ (voiture.prixMoyenPlein / 100) | number_format(2, '.', ' ')}}€</td>
                <td>{{ (voiture.prixMoyenLitre / 100) | number_format(2, '.', ' ') }}€</td>
            </tr>
        </tbody>
            
    </table>
        <a class="btn btn-default btn-sm" role="button" href="{{ path('app_voiture_index') }}">Retour à la liste</a>

    <h2 class="mt-5">Liste des pleins</h2>
    {% if voiture.pleins %}
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Date {{ order('date') }}</th>
                <th>Quantite {{ order('quantite') }}</th>
                <th>Prix {{ order('prix') }}</th>
                <th>Prix au litre {{ order('prix_au_litre') }}</th>
                <th>Kilometrage {{ order('kilometrage') }}</th>
                <th>Kilomètres parcourus {{ order('kilometre_parcourus') }}</th>
                <th>Station {{ order('station') }}</th>
            </tr>
        </thead>
        <tbody>
        {% for plein in voiture.pleins %}
            <tr>
            <th>{{ loop.index }}</th>
                <td>{{ plein.date ? plein.date|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY' - 'H'h'mm") : '' }}</td>
                <td>{{ (plein.quantite / 100.0) | number_format(2, '.', ' ') }}L</td>
                <td>{{ (plein.prix / 100.0) | number_format(2, '.', ' ')}}€</td>
                <td>{{ plein.prixAuLitre | number_format(3, '.', ' ')}}€</td>
                <td>{{ plein.kilometrage | number_format(0, '.', ' ')}} km</td>
                <td>
                    {% if voiture.kilometresParcourus(plein) == 0 %}
                        ~
                    {% else %}
                        {{ voiture.kilometresParcourus(plein) }} km
                    {% endif %}
                </td>
                <td>{{ plein.station }}</td>

            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}

{% endblock %}